ci: update system
- nixConfig to always trust cache
- update ci to handle errors

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -17,7 +17,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install Nix
-        uses: cachix/install-nix-action@v27
+        uses: cachix/install-nix-action@v30
         with:
           extra_nix_config: |
             experimental-features = nix-command flakes
@@ -30,14 +30,24 @@ jobs:
 
       - name: Build All Configurations
         run: |
+          failed=0
+
           echo ">> Discovering NixOS Configurations..."
-          for host in $(nix eval --json .#nixosConfigurations --apply builtins.attrNames | jq -r '.[]'); do
+          for host in $(nix eval --json .#nixosConfigurations --apply builtins.attrNames --accept-flake-config | jq -r '.[]'); do
             echo "Building NixOS host: $host"
-            nix build .#nixosConfigurations."$host".config.system.build.toplevel --print-build-logs
+            if ! nix build .#nixosConfigurations."$host".config.system.build.toplevel --print-build-logs --accept-flake-config; then
+              echo "::error title=Build Failed::Failed to build NixOS host: $host"
+              failed=1
+            fi
           done
 
           echo ">> Discovering Home Manager Configurations..."
-          for user in $(nix eval --json .#homeConfigurations --apply builtins.attrNames | jq -r '.[]'); do
+          for user in $(nix eval --json .#homeConfigurations --apply builtins.attrNames --accept-flake-config | jq -r '.[]'); do
             echo "Building Home Manager profile: $user"
-            nix build .#homeConfigurations."$user".activationPackage --print-build-logs
+            if ! nix build .#homeConfigurations."$user".activationPackage --print-build-logs --accept-flake-config; then
+              echo "::error title=Build Failed::Failed to build Home Manager profile: $user"
+              failed=1
+            fi
           done
+
+          exit $failed
